Task4Linkerp/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using Task4Linkerp.Models.Srvices;
using Task4Linkerp.Models;
using Task4Linkerp.ViewModel.City;

namespace Task4Linkerp.Controllers
{
    public class CityController : Controller
    {
        private readonly IRepository<City> _cityRepository;
        private readonly IRepository<Region> _regionRepository;

        public CityController(IRepository<City> cityRepository,IRepository<Region> regionRepository)
        {
            _cityRepository = cityRepository;
            _regionRepository = regionRepository;
        }

        public async Task<IActionResult> Index(string? searchString)
        {

           var cities = await _cityRepository.FilterByAsync(searchString);
            var cityViewModels=new List<AllCitiesViewModel>();

            foreach(var city in cities)
            {
                cityViewModels.Add(new AllCitiesViewModel(city.Id, city.Code, city.NameEN,city.NameAR));
            }

            return View(cityViewModels);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CityViewModel cityViewModel)
        {

            if (!ModelState.IsValid)
            {
                return View(cityViewModel);
            }

            try
            {
                City city=new City(cityViewModel.Code,cityViewModel.NameEN,cityViewModel.NameAR,cityViewModel.Active,cityViewModel.Notes);

                _cityRepository.Create(city);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(cityViewModel);
            }

        }
        public IActionResult Details(int id)
        {
            if (!ModelState.IsValid)
                return View(id);
            try
            {
                City? city = _cityRepository.GetById(id);
                if (city != null)
                {
                    ViewBag.Regions = city.Regions;
                    DetailsCityViewModel detailsCityViewModel = new DetailsCityViewModel(city.Id,city.Code, city.NameEN, city.NameAR, city.Active, city.Notes);
                    return View(detailsCityViewModel);  
                }
                return View(id);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(id);
            }

        }

        public IActionResult Edit(int id)
        {
            if (!ModelState.IsValid)
                return View(id);
            try
            {
                City? city = _cityRepository.GetById(id);
                if (city != null)
                    return View(city);
                
                return View(id);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(id);
            }
        }
        [HttpPost]
        public IActionResult Edit(City city)
        {

            if (!ModelState.IsValid)
                return View(city);
            try
            {
                _cityRepository.Update(city);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(city);
            }
        }
        public IActionResult Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return View(id);
            }
            try
            {
                _cityRepository.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(id);
            }

        }
    }
}

Task4Linkerp/Controllers/RegionController.cs
using Microsoft.AspNetCore.Mvc;
using Task4Linkerp.Models.Srvices;
using Task4Linkerp.Models;
using Task4Linkerp.ViewModel.Region;

namespace Task4Linkerp.Controllers
{
    public class RegionController : Controller
    {
        private readonly IRepository<Region> _regionRepository;
        private readonly IRepository<City> _cityRepository;
      

        public RegionController(IRepository<Region> regionRepository, IRepository<City> cityRepository)
        {
            _regionRepository = regionRepository;
            _cityRepository= cityRepository;
           
        }
        public IActionResult Index(string? searchString)
        {
            IEnumerable<Region> regions =_regionRepository.GetAll();
            List<AllRegionsViewModel> allRegions = new List<AllRegionsViewModel>();
            foreach(var region in regions)
            {
                allRegions.Add(new AllRegionsViewModel(region.Id,region.Code, region.NameEN, region.NameAR));
            }


            return View(allRegions);
        }
        public IActionResult Create()
        {
            ViewBag.Cities = _cityRepository.GetAll();

            return View();
        }
        [HttpPost]

        public IActionResult Create(AddRegionVeiwModel addRegionVeiwModel)
        {


            try
            {
                Region region = new Region(addRegionVeiwModel.Code, addRegionVeiwModel.NameEN, addRegionVeiwModel.NameAR, addRegionVeiwModel.CityId);
                _regionRepository.Create(region);
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(addRegionVeiwModel);
            }

        }
        public IActionResult Details(int id)
        {


            try
            {
                Region? region = _regionRepository.GetById(id);
                if (region != null)
                {
                    ViewBag.City = region.City;
                    return View(new DetailsRegionViewModel(region.Id, region.Code, region.NameEN, region.NameAR));
                }
                    
               
                return View(id);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(id);
            }

        }
       
        public IActionResult Edit(int id)
        {
            if (!ModelState.IsValid)
                return View(id);

            try
            {
                Region? region= _regionRepository.GetById(id);
                if (region != null)
                    return View(region);
                return View(id);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(id);
            }
        }
        [HttpPost]
        public IActionResult Edit(Region region)
        {
            try
            {
                _regionRepository.Update(region);
                  return RedirectToAction("Index");
               
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(region);
            }
        }
        public IActionResult Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return View(id);
            }
            try
            {
                _regionRepository.Delete(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(id);
            }

        }
    }
}

Task4Linkerp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@using System.Globalization



@inject IViewLocalizer localizer


@{
    var isRTL = CultureInfo.CurrentCulture.Name.StartsWith("ar");
}
<!DOCTYPE html>
<html lang="@(isRTL ? "ar" : "en")" dir="@(isRTL ? "RTL" : "LTR")">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task4Linkerp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
     @if (isRTL)
        {
            @*<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">*@
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU" crossorigin="anonymous">

        }
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Task4Linkerp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item ">
                            <a class="nav-link active text-white"  asp-controller="City" asp-action="Index">@localizer["Home"]</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link active text-white" asp-controller="City" asp-action="Index">@localizer["All Cities"]</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link active text-white" asp-controller="Region" asp-action="Index">@localizer["All Regions"]</a>
                        </li>
                         <li>
                            <a class="nav-link active text-white" asp-controller="City" asp-action="Create" class="dropdown-item d-flex align-items-center">
                                    
                                    @localizer["Create New City"]
                            </a>
                          </li>
                        <li>
                            <a class="nav-link active text-white" asp-controller="Region" asp-action="Create" class="dropdown-item d-flex align-items-center">

                                @localizer["Create New Region"]
                            </a>
                        </li>
                        <li>
                            <div >
                                <form asp-action="Index" asp-controller="City" method="get" class="d-flex">
                                   
                                    <input class="form-control me-2" name="searchString" type="search" placeholder="Search" aria-label="Search" />

                                    <button type="submit" class="btn btn-outline-success w-50 align-items-center text-white">@localizer["Search"]</button>
                                
                                </form>
                            </div>
                           
                        </li>
                        @*localization*@
                         <li>
                           <div>
                                <partial name="_SelectLanguage" />
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Task4Linkerp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Task4Linkerp/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Builder;
@using Microsoft.AspNetCore.Localization;
@using Microsoft.AspNetCore.Http.Features;
@using Microsoft.AspNetCore.Mvc.Localization;
@using Microsoft.Extensions.Options;

@inject IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> options

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultures = options.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<div class="dropdown-item d-flex align-items-center">
    <form method="post" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@returnUrl">
        <select class="form-select " name="culture"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultures"
                onchange="this.form.submit();">
        </select>
    </form>
</div>